### ISSUE TITLE
Crash on join

### ISSUE THREAD

**Issue by mawoka-myblock** [OneLemonyBoi/LemonLib#1]
```
[22Mai2021 09:11:00.809] [Server thread/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class onelemonyboi/lemonlib/rewards/PatreonJSON for invalid dist DEDICATED_SERVER
[22Mai2021 09:11:00.811] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class onelemonyboi/lemonlib/rewards/PatreonJSON for invalid dist DEDICATED_SERVER
        Index: 2
        Listeners:
                0: NORMAL
                1: ASM: class onelemonyboi.miniutilities.items.unstable.UnstableIngot playertick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                2: net.minecraftforge.eventbus.EventBus$$Lambda$2805/0x0000000840a4cc40@1ccea8ce
                3: ASM: class twilightforest.TFTickHandler playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                4: ASM: vazkii.quark.content.tweaks.module.CampfiresBoostElytraModule@3c9842c onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                5: ASM: vazkii.quark.content.tweaks.module.CompassesWorkEverywhereModule@25bb0b08 onUpdate(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                6: ASM: vazkii.quark.content.tweaks.module.EnhancedLaddersModule@433d9a5f onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                7: ASM: vazkii.quark.content.tweaks.module.InfinityBucketModule@5b463c93 playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                8: ASM: mekanism.common.CommonPlayerTickHandler@2b8f2379 onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                9: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@46fc4ff8 tickStart(Lnet/minecraftforge/event/TickEvent;)V
java.lang.RuntimeException: Attempted to load class onelemonyboi/lemonlib/rewards/PatreonJSON for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at onelemonyboi.lemonlib.rewards.PatreonRewards.PatreonRewardsHandling(PatreonRewards.java:57)
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85)
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:196)
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404)
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.base/java.lang.Thread.run(Thread.java:829)

[22Mai2021 09:11:00.822] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 410d178d-31fe-4863-8c96-16315d8bba8f
[22Mai2021 09:11:00.825] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /93.238.108.106:48524
net.minecraft.crash.ReportedException: Ticking player
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:467) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.RuntimeException: Attempted to load class onelemonyboi/lemonlib/rewards/PatreonJSON for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge.jar:36.1]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at onelemonyboi.lemonlib.rewards.PatreonRewards.PatreonRewardsHandling(PatreonRewards.java:57) ~[lemonlib:1.3.4]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85) ~[forge:?]
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:196) ~[?:?]
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
        ... 9 more
[22Mai2021 09:11:00.923] [Server thread/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class onelemonyboi/lemonlib/rewards/PatreonJSON for invalid dist DEDICATED_SERVER
[22Mai2021 09:11:00.924] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class onelemonyboi/lemonlib/rewards/PatreonJSON for invalid dist DEDICATED_SERVER
        Index: 2
        Listeners:
                0: NORMAL
                1: ASM: class onelemonyboi.miniutilities.items.unstable.UnstableIngot playertick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                2: net.minecraftforge.eventbus.EventBus$$Lambda$2805/0x0000000840a4cc40@1ccea8ce
                3: ASM: class twilightforest.TFTickHandler playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                4: ASM: vazkii.quark.content.tweaks.module.CampfiresBoostElytraModule@3c9842c onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                5: ASM: vazkii.quark.content.tweaks.module.CompassesWorkEverywhereModule@25bb0b08 onUpdate(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                6: ASM: vazkii.quark.content.tweaks.module.EnhancedLaddersModule@433d9a5f onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                7: ASM: vazkii.quark.content.tweaks.module.InfinityBucketModule@5b463c93 playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                8: ASM: mekanism.common.CommonPlayerTickHandler@2b8f2379 onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                9: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@46fc4ff8 tickStart(Lnet/minecraftforge/event/TickEvent;)V
java.lang.RuntimeException: Attempted to load class onelemonyboi/lemonlib/rewards/PatreonJSON for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at onelemonyboi.lemonlib.rewards.PatreonRewards.PatreonRewardsHandling(PatreonRewards.java:57)
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85)
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:196)
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404)
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.base/java.lang.Thread.run(Thread.java:829)

[22Mai2021 09:11:00.936] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 716e4149-972c-42fc-9645-a3a001e6c58d
[22Mai2021 09:11:00.937] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /93.238.108.106:48524
net.minecraft.crash.ReportedException: Ticking player
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:467) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.RuntimeException: Attempted to load class onelemonyboi/lemonlib/rewards/PatreonJSON for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge.jar:36.1]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at onelemonyboi.lemonlib.rewards.PatreonRewards.PatreonRewardsHandling(PatreonRewards.java:57) ~[lemonlib:1.3.4]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85) ~[forge:?]
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:196) ~[?:?]
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
        ... 9 more
[22Mai2021 09:11:00.970] [Server thread/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class onelemonyboi/lemonlib/rewards/PatreonJSON for invalid dist DEDICATED_SERVER
[22Mai2021 09:11:00.971] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class onelemonyboi/lemonlib/rewards/PatreonJSON for invalid dist DEDICATED_SERVER
        Index: 2
        Listeners:
                0: NORMAL
                1: ASM: class onelemonyboi.miniutilities.items.unstable.UnstableIngot playertick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                2: net.minecraftforge.eventbus.EventBus$$Lambda$2805/0x0000000840a4cc40@1ccea8ce
                3: ASM: class twilightforest.TFTickHandler playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                4: ASM: vazkii.quark.content.tweaks.module.CampfiresBoostElytraModule@3c9842c onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                5: ASM: vazkii.quark.content.tweaks.module.CompassesWorkEverywhereModule@25bb0b08 onUpdate(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                6: ASM: vazkii.quark.content.tweaks.module.EnhancedLaddersModule@433d9a5f onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                7: ASM: vazkii.quark.content.tweaks.module.InfinityBucketModule@5b463c93 playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                8: ASM: mekanism.common.CommonPlayerTickHandler@2b8f2379 onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
                9: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@46fc4ff8 tickStart(Lnet/minecraftforge/event/TickEvent;)V
java.lang.RuntimeException: Attempted to load class onelemonyboi/lemonlib/rewards/PatreonJSON for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at onelemonyboi.lemonlib.rewards.PatreonRewards.PatreonRewardsHandling(PatreonRewards.java:57)
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85)
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:196)
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404)
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.base/java.lang.Thread.run(Thread.java:829)

[22Mai2021 09:11:00.983] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID e0a051ee-fc72-4d12-b388-2d9acfd73a41
[22Mai2021 09:11:00.984] [Server thread/WARN] [net.minecraft.network.NetworkSystem/]: Failed to handle packet for /93.238.108.106:48524
net.minecraft.crash.ReportedException: Ticking player
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:467) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.RuntimeException: Attempted to load class onelemonyboi/lemonlib/rewards/PatreonJSON for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge.jar:36.1]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at onelemonyboi.lemonlib.rewards.PatreonRewards.PatreonRewardsHandling(PatreonRewards.java:57) ~[lemonlib:1.3.4]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
        at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85) ~[forge:?]
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:196) ~[?:?]
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
        ... 9 more
```
Reproduce: Install The required mods and add them to a forge-server. Then try to join, and it will return the error above and the client says something like `Internal Server Error` or so.
```
• minecraft forge-1.16.5-36.1.0-server.jar : minecraft (1.16.5) - 1
• mods_folder TConstruct-1.16.5-3.0.3.126.jar : tconstruct (3.0.3.126) - 1
• mods_folder miniutilities-1.0.1-alpha.jar : miniutilities (1.0.1-alpha) - 1
• mods_folder theoneprobe-1.16-3.0.7.jar : theoneprobe (1.16-3.0.7) - 1
• mods_folder ImmersiveEngineering-1.16.5-4.2.4-134.jar : immersiveengineering (1.16.5-4.2.4-134) - 1
• mods_folder worldedit-mod-7.2.5-dist.jar : worldedit (7.2.5+57d5ac9) - 1
• mods_folder MekanismGenerators-1.16.5-10.0.21.448.jar : mekanismgenerators (10.0.21) - 1
• mods_folder jei-1.16.5-7.6.4.87.jar : jei (7.6.4.87) - 1
• mods_folder Mekanism-1.16.5-10.0.21.448.jar : mekanism (10.0.21) - 1
• maven_libs forge-1.16.5-36.1.0-universal.jar : forge (36.1.0) - 1
• mods_folder lemonlib-1.3.4.jar : lemonlib (1.3.4) - 1
• mods_folder curios-forge-1.16.5-4.0.5.1.jar : curios (1.16.5-4.0.5.1) - 1
• mods_folder twilightforest-1.16.5-4.0.426-universal.jar : twilightforest (NONE) - 1
• mods_folder Mantle-1.16.5-1.6.92.jar : mantle (1.6.92) - 1
• mods_folder create-mc1.16.5_v0.3.1c.jar : create (mc1.16.5_v0.3.1c+151) - 1
• mods_folder chiselsandbits-0.3.4-RELEASE.jar : chiselsandbits (NONE) - 1
• mods_folder SuperTools-1.2_1.16.5.jar : supertools (1.2) - 1
• mods_folder journeymap-1.16.5-5.7.1.jar : journeymap (5.7.1) - 1
• mods_folder CTM-MC1.16.1-1.1.2.6.jar : ctm (MC1.16.1-1.1.2.6) - 1
• mods_folder AutoRegLib-1.6-47.jar : autoreglib (1.6-47) - 1
• mods_folder Quark-r2.4-311.jar : quark (r2.4-311) - 1
• mods_folder appliedenergistics2-8.2.0.jar : appliedenergistics2 (8.2.0) - 1
• mods_folder StorageDrawers-1.16.3-8.2.2.jar : storagedrawers (8.2.2) - 1
```

**Comment by OneLemonyBoi** [comment]
fixed
