### ISSUE TITLE
Crash on launch 1.19.2

### ISSUE THREAD

**Issue by JadeFalcon** [OneLemonyBoi/LemonLib#3]
[crash-2023-07-14_04.52.46-client.txt](https://github.com/OneLemonyBoi/LemonLib/files/12050089/crash-2023-07-14_04.52.46-client.txt)

Here is the crashlog.

I also found this in the debug.txt:

[14Jul2023 04:52:42.682] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: lemonlib, class onelemonyboi.lemonlib.LemonLib
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.13.jar%23591!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.13.jar%23590!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/network/chat/TextComponent
	at onelemonyboi.lemonlib.LemonLib.<init>(LemonLib.java:25) ~[lemonlib-3.0.1.jar%23481!/:3.0.1]
	... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.network.chat.TextComponent
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at onelemonyboi.lemonlib.LemonLib.<init>(LemonLib.java:25) ~[lemonlib-3.0.1.jar%23481!/:3.0.1]
	... 14 more

**Comment by OneLemonyBoi** [comment]
fixed
