### ISSUE TITLE
Error loading mods lemon lib 1.19.2

### ISSUE THREAD

**Issue by SolAstral** [OneLemonyBoi/LemonLib#4]
```
java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.2.0-universal.jar%23164!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.2.0-universal.jar%23164!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:438) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:885) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23159!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
```

Error from the crash log ^^^

**Comment by ukmcplyr** [comment]
I think I've hit the same crash though hard to be certain from the truncated crash log.

Cause:

```
[27/07/2023 08:11:59 am] 	Caused by 0: java.lang.reflect.InvocationTargetException
[27/07/2023 08:11:59 am] 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[...]
[27/07/2023 08:11:59 am] 	Caused by 1: java.lang.NoClassDefFoundError: net/minecraft/network/chat/TextComponent
[27/07/2023 08:11:59 am] 		at onelemonyboi.lemonlib.LemonLib.<init>(LemonLib.java:25) ~[lemonlib-3.0.1.jar%23145!/:3.0.1] {re:classloading}
```

Full crash log [here](https://pste.ch/tefusitifa.sql).  Does this tally with the crash you saw @SolAstral ?

Reproducible with just:

- forge-1.19.2-43.2.14
- curios-forge-1.19.2-5.1.4.1.jar
- lemonlib-3.0.1.jar
- miniutilities-3.0.0.jar

**Comment by Puky-X** [comment]
I ran into the same error. How to solve?

**Comment by 2ndkirbyever** [comment]
I'm having the same problem. Lemon Lib 3.0.1 crashes the game before it can fully launch.
[Full crash log](https://github.com/OneLemonyBoi/LemonLib/files/12208491/crash-2023-07-29_22.56.29-fml.txt)

**Comment by magcicada** [comment]
Fixed one is [here](https://github.com/magcicada/LemonLib/releases/tag/1.19.2)

**Comment by magcicada** [comment]
![image](https://github.com/OneLemonyBoi/LemonLib/assets/45464670/c4992d35-dda6-4e6d-89a4-546623c4da3f)
I test that in the modpack with over 280 mods and no errors were found at the moment.

**Comment by zISKo666** [comment]
Hey there,
would you mind to upload this fix to curseforge and modrinth so others are able to download it from the desired location!?

Thank you
